### ISSUE TITLE
Nova Support

### ISSUE THREAD

**Issue by Kingorgg** [tomvlk/sweet-orm#1]
Will this work on Dave's Nova? 

As I noticed the nova-sweet-orm is a package, which I believe is for luckycyborg's nova. If so, how would the database configuration work? 

Would it work with the Nova's config file, or would I have to set up the sweet-orm's database config separately?

I know this is not really an "issue", but I have no other way of contacting you to ask.

**Comment by tomvlk** [comment]
I will have to look into that later.., I haven't watcht the Nova (the real one) since some time ago. We can of course make some glue package or whatever.

**Comment by tomvlk** [comment]
You can do it easely with the following changes (to nova, dave's version):

composer.json:
Add the requirement (min version used should be 0.5.2:
```
"tomvlk/sweet-orm": "0.5.*"
```


Config.php: Inject the PDO connection into SweetORM, this also registers the Annotations required.
```php
// On the end, after session init:

        /**
         * Sweet ORM
         */
        \SweetORM\ConnectionManager::injectConnection(\Helpers\Database::get());
```


Define your models in the Model namespace like this:

Models/Car.php
```php
<?php
namespace App\Models;
use SweetORM\Entity;
use SweetORM\Structure\Annotation\Column;
use SweetORM\Structure\Annotation\EntityClass;
use SweetORM\Structure\Annotation\Table;
/**
 * Car Entity.
 * @EntityClass()
 * @Table(name="nova_car")
 */
class Car extends Entity {
  /**
   * @Column(type="integer", primary=true)
   */
  public $carid;
}
```


And then you could ask the model everything in your controllers or anywere:

```php
        $result = Car::find()->all();

        echo "<pre>";
        var_dump($result);
        echo "</pre>";
```


**It would be nice to make some sort of documentation for implementing in other frameworks** Because this right now is not that nice, but the orm is still in development, the core should be stable (create, save, fetching).

**Comment by Kingorgg** [comment]
Thanks, I'll have a play around with it and report any bugs if I find any.

**Comment by tomvlk** [comment]
Perfect, let me know if there is something not right, or logic, or maybe needs some improvement.
From now I'm also going to use the ORM itself for a project, so you can expect some improvements on several points.
